version: '3.0'
services:
  application:
    build:
      context: .
      args:
        - NODE_ENV=development NODE_PATH=/program
        - HEADLESS_BROSWER=true
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
